<!--catch 块会捕捉到 try 块中的错误，并执行代码来处理它-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>捕获错误</title>
</head>
<body>

<script>
    var txt = "";
    function message() {
        try{
            adddlert("Welcome guest!");
        }
        catch (e) {
            txt = "本页有一个错误。\n\n";
            txt += "错误描述：" + e.message + "\n\n";
            txt += "点击确定继续。\n\n";
            alert(txt);
        }
    }
</script>

<input type="button" value="查看消息" onclick="message()">
</body>
</html>